 - id: tofu-docs
   name: tofu-docs
   description: Generate documentation for the project
   language: docker_image
   entry: docker.io/70696b61726f/tofu-docs:v0.1.0 --module_path=/src --changed_exit_code=1
   files: (README.md|\.tf)$
   pass_filenames: false
