name: Build
run-name: ${{ github.event_name }}-${{ github.ref_name }}-${{ github.actor }}

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: .pre-commit-trivy-cache
          key: trivy-${{ steps.date.outputs.date }}
          restore-keys: |
            trivy-

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine tag
        id: tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAG="latest"
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            TAG="dev"
          elif [[ "${GITHUB_REF_NAME}" == v* ]]; then
            TAG="${GITHUB_REF_NAME}"
          else
            echo "::error:::Invalid branch name: ${GITHUB_REF_NAME}"
            exit 1
          fi
          REPO="${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}"
          echo "::notice::Building as ${REPO}:${TAG}"
          echo "repo=${REPO}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.repo }}:${{ steps.tag.outputs.tag }}
